name: Unity Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Create Unity manual activation file
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        id: activation
        uses: game-ci/unity-request-activation-file@v2
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation
          path: ${{ steps.activation.outputs.filePath }}
          if-no-files-found: error
